#!/usr/bin/env bash

set -E

DIRS="syntax indent compiler autoload ftplugin after/syntax after/indent after/ftplugin plugin syntax_checkers"
DIRS_BASIC="syntax compiler indent after/syntax after/indent plugin syntax_checkers"
DIRS_ALL="syntax indent compiler autoload ftplugin after plugin syntax_checkers"
DIRS_SYNTAX="syntax ftplugin after/syntax after/ftplugin indent plugin syntax_checkers"
DIRS_JAVASCRIPT="${DIRS} extras"
DIRS_RM="$DIRS_JAVASCRIPT"

OUTPUT=""

output() {
  OUTPUT="$OUTPUT$1"
  printf -- "$1"
}

download() {
  for pack in $1; do
    path="$(printf "$pack" | cut -d ':' -f 2)"
    dir="tmp/$(printf "$path" | cut -d '/' -f 2)"
    rm -rf "$dir"
    (mkdir -p "$dir" && curl --silent -L https://codeload.github.com/$path/tar.gz/master | tar -zx -C "$dir" --strip 1 && printf '.') &
  done

  wait
}

extract() {
  printf "\n"

  cat config.vim >> tmp/polyglot.vim

  for pack in $1; do
    name="$(printf "$pack" | cut -d ':' -f 1)"
    path="$(printf "$pack" | cut -d ':' -f 2)"
    dir="tmp/$(printf "$path" | cut -d '/' -f 2)"
    directories="DIRS$(printf "$pack" | cut -d ':' -f 3)"
    subtree="$(printf "$pack" | cut -d ':' -f 4)"
    output "- [$name](https://github.com/$path) ("

    subdirs=""
    for subdir in ${!directories}; do
      if [ -d "${dir}${subtree:-/}${subdir}" ]; then
        base="$(basename "$subdir")"
        if [[ "$subdirs" != *"$base"* ]]; then
          subdirs="$subdirs, $base"
        fi

        copy_dir "${dir}${subtree}" "$subdir" "$name"
      fi
    done

    for f in ${dir}/ftdetect/*; do
      (
        echo "augroup filetypedetect";
        echo '" '"$pack";
        cat "${f}";
        echo "augroup END";
        echo
      ) >> tmp/polyglot.vim;
    done

    output "${subdirs##, })\n"
  done

  mv tmp/polyglot.vim ftdetect/

  for pack in $1; do
    name="$(printf "$pack" | cut -d ':' -f 1)"
    path="$(printf "$pack" | cut -d ':' -f 2)"
    dir="tmp/$(printf "$path" | cut -d '/' -f 2)"
    subtree="$(printf "$pack" | cut -d ':' -f 4)"
  done
}

copy_dir() {
  for file in $(find "$1/$2" -type f \( -name '*.vim' -o -name '*.vital' \)); do
    file_path="$(dirname "${file##$1/}")"
    mkdir -p "$file_path"
    touch "$file_path/$(basename "$file")"

    # Use comma instead of / to handle cases like c/c++
    if [[ $file == *".vim" ]]; then
      touch "$file_path/$(basename "$file")"
      sed -e "s,%%PACK%%,$3," -e "/%%CONTENT%%/{r $file" -e "d;}" plugin_guard.vim.template >> "$file_path/$(basename "$file")"
    else
      cp "$file" "$file_path/$(basename "$file")"
    fi
  done
}

update_readme() {
  OLD_README="$(cat README.md)"

  ed README.md <<- EOF
/Language packs
+2kb
/##
'b,-2c
$(printf -- "$OUTPUT" | sort)
.
w
q
EOF

}

# Rubix Updates:
#   css:JulesWang/css.vim -> hail2u/vim-css3-syntax
# + csv:chrisbra/csv.vim
# + flatbuffers:zchee/vim-flatbuffers
# - go:fatih/vim-go
# + jinja:Glench/Vim-Jinja2-Syntax
# + jslib:othree/javascript-libraries-syntax.vim
#   julia:dcjones/julia-minimalist-vim -> JuliaLang/julia-vim
# - scss:cakebaker/scss-syntax.vim

PACKS="
  apiblueprint:sheerun/apiblueprint.vim
  applescript:vim-scripts/applescript.vim
  yaml:stephpy/vim-yaml
  ansible:pearofducks/ansible-vim
  arduino:sudar/vim-arduino-syntax
  blade:jwalton512/vim-blade
  c++11:octol/vim-cpp-enhanced-highlight
  c/c++:vim-jp/vim-cpp
  caddyfile:joshglendenning/vim-caddyfile
  cjsx:mtscout6/vim-cjsx
  clojure:guns/vim-clojure-static
  coffee-script:kchmck/vim-coffee-script
  cryptol:victoredwardocallaghan/cryptol.vim
  crystal:rhysd/vim-crystal
  cql:elubow/cql-vim
  css:hail2u/vim-css3-syntax
  csv:chrisbra/csv.vim
  cucumber:tpope/vim-cucumber
  dart:dart-lang/dart-vim-plugin
  dockerfile:docker/docker::/contrib/syntax/vim/
  elixir:elixir-lang/vim-elixir
  elm:lambdatoast/elm.vim
  emberscript:yalesov/vim-ember-script
  emblem:yalesov/vim-emblem
  erlang:vim-erlang/vim-erlang-runtime
  fish:dag/vim-fish
  flatbuffers:zchee/vim-flatbuffers
  git:tpope/vim-git
  glsl:tikhomirov/vim-glsl
  gnuplot:vim-scripts/gnuplot-syntax-highlighting
  groovy:vim-scripts/groovy.vim
  haml:sheerun/vim-haml
  handlebars:mustache/vim-mustache-handlebars
  haskell:neovimhaskell/haskell-vim
  haxe:yaymukund/vim-haxe
  html5:othree/html5.vim
  i3:PotatoesMaster/i3-vim-syntax
  jasmine:glanotte/vim-jasmine
  javascript:pangloss/vim-javascript:_JAVASCRIPT
  json:elzr/vim-json
  jinja:Glench/Vim-Jinja2-Syntax
  jslib:othree/javascript-libraries-syntax.vim
  jst:briancollins/vim-jst
  jsx:mxw/vim-jsx:_ALL
  julia:JuliaLang/julia-vim
  kotlin:udalov/kotlin-vim
  latex:LaTeX-Box-Team/LaTeX-Box
  less:groenewege/vim-less
  liquid:tpope/vim-liquid
  livescript:gkz/vim-ls
  lua:tbastos/vim-lua
  mako:sophacles/vim-bundle-mako
  markdown:plasticboy/vim-markdown:_SYNTAX
  mathematica:rsmenon/vim-mathematica
  nginx:othree/nginx-contrib-vim
  nim:zah/nim.vim:_BASIC
  nix:spwhitt/vim-nix
  objc:b4winckler/vim-objc
  ocaml:jrk/vim-ocaml
  octave:vim-scripts/octave.vim--
  opencl:petRUShka/vim-opencl
  perl:vim-perl/vim-perl
  pgsql:exu/pgsql.vim
  php:StanAngeloff/php.vim
  plantuml:aklt/plantuml-syntax
  powershell:PProvost/vim-ps1
  protobuf:uarun/vim-protobuf
  pug:digitaltoad/vim-pug
  puppet:voxpupuli/vim-puppet
  purescript:raichoo/purescript-vim
  python:mitsuhiko/vim-python-combined
  python-compiler:aliev/vim-compiler-python
  qml:peterhoeg/vim-qml
  r-lang:vim-scripts/R.vim
  raml:IN3D/vim-raml
  ragel:jneen/ragel.vim
  rspec:sheerun/rspec.vim
  ruby:vim-ruby/vim-ruby
  rust:rust-lang/rust.vim
  sbt:derekwyatt/vim-sbt
  scala:derekwyatt/vim-scala
  slim:slim-template/vim-slim
  solidity:ethereum/vim-solidity
  stylus:wavded/vim-stylus
  swift:keith/swift.vim
  sxhkd:baskerville/vim-sxhkdrc
  systemd:kurayama/systemd-vim-syntax
  terraform:hashivim/vim-terraform
  textile:timcharper/textile.vim
  thrift:solarnz/thrift.vim
  tmux:keith/tmux.vim
  tomdoc:wellbredgrapefruit/tomdoc.vim
  toml:cespare/vim-toml
  twig:lumiliet/vim-twig
  typescript:leafgarland/typescript-vim
  vala:arrufat/vala.vim
  vbnet:vim-scripts/vbnet.vim
  vcl:smerrill/vcl-vim-plugin
  vue:posva/vim-vue
  vm:lepture/vim-velocity
  xls:vim-scripts/XSLT-syntax
  yard:sheerun/vim-yardoc
"

rm -rf tmp
rm -rf $DIRS_RM
mkdir tmp

printf "Downloading packs..."
download "$PACKS"
extract "$PACKS"
update_readme

rm -rf tmp
